name: Coding style check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install pycparser
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install pycparser
      - name: install bubulle
        run: sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/aureliancnx/Bubulle-Norminette/master/install_bubulle.sh)"
      - name: run checks
        run: bubulle
